# Build Configuration for Chat P2P
# This file contains build settings and configurations

app:
  name: "Chat P2P"
  package_name: "com.chatp2p.app"
  version: "1.0.0"
  build_number: 1
  description: "Decentralized P2P Chat Application"

android:
  min_sdk_version: 21
  target_sdk_version: 34
  compile_sdk_version: 34
  
  # Build variants
  build_types:
    debug:
      debuggable: true
      minify_enabled: false
      shrink_resources: false
    release:
      debuggable: false
      minify_enabled: true
      shrink_resources: true
      proguard_files:
        - "proguard-android-optimize.txt"
        - "proguard-rules.pro"

  # Signing configuration
  signing:
    debug:
      store_file: "debug.keystore"
      store_password: "android"
      key_alias: "androiddebugkey"
      key_password: "android"
    release:
      store_file: "release.keystore"
      store_password: "${KEYSTORE_PASSWORD}"
      key_alias: "${KEY_ALIAS}"
      key_password: "${KEY_PASSWORD}"

  # Permissions
  permissions:
    - "android.permission.INTERNET"
    - "android.permission.ACCESS_NETWORK_STATE"
    - "android.permission.ACCESS_WIFI_STATE"
    - "android.permission.CHANGE_WIFI_STATE"
    - "android.permission.BLUETOOTH"
    - "android.permission.BLUETOOTH_ADMIN"
    - "android.permission.ACCESS_COARSE_LOCATION"
    - "android.permission.ACCESS_FINE_LOCATION"
    - "android.permission.CAMERA"
    - "android.permission.RECORD_AUDIO"
    - "android.permission.WRITE_EXTERNAL_STORAGE"
    - "android.permission.READ_EXTERNAL_STORAGE"
    - "android.permission.WAKE_LOCK"
    - "android.permission.FOREGROUND_SERVICE"

ios:
  deployment_target: "12.0"
  
  # Info.plist configurations
  info_plist:
    NSCameraUsageDescription: "This app needs camera access to scan QR codes and take photos"
    NSMicrophoneUsageDescription: "This app needs microphone access for voice messages"
    NSLocationWhenInUseUsageDescription: "This app needs location access to discover nearby peers"
    NSBluetoothAlwaysUsageDescription: "This app uses Bluetooth to discover nearby devices"
    NSLocalNetworkUsageDescription: "This app needs local network access for P2P connections"
    
  # Capabilities
  capabilities:
    - "com.apple.developer.networking.multicast"
    - "com.apple.developer.networking.wifi-info"

# Build optimization
optimization:
  tree_shaking: true
  split_debug_info: true
  obfuscate: true
  
  # Asset optimization
  assets:
    compress_images: true
    optimize_fonts: true
    remove_unused_assets: true

# Dependencies versions
dependencies:
  flutter_sdk: ">=3.0.0"
  dart_sdk: ">=3.0.0"
  
  # Core dependencies
  cupertino_icons: "^1.0.2"
  provider: "^6.0.5"
  get_it: "^7.6.4"
  dartz: "^0.10.1"
  equatable: "^2.0.5"
  
  # Storage
  hive: "^2.2.3"
  hive_flutter: "^1.1.0"
  sqflite: "^2.3.0"
  path_provider: "^2.1.1"
  
  # Network & WebRTC
  flutter_webrtc: "^0.9.46"
  dio: "^5.3.2"
  connectivity_plus: "^5.0.1"
  
  # UI & UX
  flutter_local_notifications: "^16.1.0"
  share_plus: "^7.2.1"
  image_picker: "^1.0.4"
  file_picker: "^6.1.1"
  
  # QR Code
  qr_flutter: "^4.1.0"
  qr_code_scanner: "^1.0.1"
  
  # Crypto & Security
  crypto: "^3.0.3"
  encrypt: "^5.0.1"
  
  # Background services
  workmanager: "^0.5.2"
  
  # Utilities
  uuid: "^4.1.0"
  intl: "^0.18.1"
  permission_handler: "^11.0.1"

# Build scripts
scripts:
  pre_build:
    - "flutter clean"
    - "flutter pub get"
    - "flutter pub run build_runner build --delete-conflicting-outputs"
  
  build_debug:
    - "flutter build apk --debug --no-tree-shake-icons"
  
  build_release:
    - "flutter build apk --release --obfuscate --split-debug-info=build/debug-info"
  
  build_bundle:
    - "flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info"
  
  build_ios:
    - "flutter build ios --release --obfuscate --split-debug-info=build/debug-info"

# Testing configuration
testing:
  unit_tests: true
  widget_tests: true
  integration_tests: true
  
  coverage:
    enabled: true
    threshold: 80
    exclude:
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/main.dart"

# Deployment
deployment:
  android:
    store: "google_play"
    track: "internal"
    
  ios:
    store: "app_store"
    testflight: true

# Environment variables
environment:
  development:
    API_BASE_URL: "https://dev-api.chatp2p.com"
    DEBUG_MODE: true
    
  staging:
    API_BASE_URL: "https://staging-api.chatp2p.com"
    DEBUG_MODE: false
    
  production:
    API_BASE_URL: "https://api.chatp2p.com"
    DEBUG_MODE: false

# Code generation
code_generation:
  hive_generator: true
  json_serializable: true
  build_runner: true

# Linting and formatting
linting:
  rules: "analysis_options.yaml"
  strict_mode: true
  
formatting:
  line_length: 120
  indent_size: 2
