name: chat_p2p
description: "Decentralized P2P Chat Application with End-to-End Encryption - Demo Version"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1

  # Core Dependencies (for demo purposes - commented out to avoid build issues)
  # crypto: ^3.0.3
  # encrypt: ^5.0.1
  # pointycastle: ^3.7.3
  # equatable: ^2.0.5
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # qr_flutter: ^4.1.0
  # qr_code_scanner: ^1.0.1
  # share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Integration Testing (commented out for demo)
  # integration_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
